'use client';
import { motion } from 'framer-motion';
import { AlertTriangle } from 'lucide-react';

export default function EmergencyAlert({ flag, reasons = [] }) {
    if (!flag) return null;

    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4, type: 'spring' }}
            className="bg-emergency text-white rounded-2xl p-6 shadow-lg shadow-emergency/25 space-y-3"
        >
            <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center shrink-0">
                    <AlertTriangle className="w-5 h-5 animate-pulse" />
                </div>
                <div>
                    <p className="text-[10px] font-bold uppercase tracking-widest opacity-80">Critical Clinical Alert</p>
                    <h3 className="text-lg font-bold">Immediate Professional Medical Attention Recommended</h3>
                </div>
            </div>

            {reasons.length > 0 && (
                <div className="bg-white/10 rounded-xl p-4 space-y-2">
                    <p className="text-xs font-bold uppercase tracking-wider opacity-80">Flagged Indicators:</p>
                    <ul className="space-y-1">
                        {reasons.map((reason, i) => (
                            <li key={i} className="text-sm flex items-start gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-white mt-1.5 shrink-0" />
                                {reason}
                            </li>
                        ))}
                    </ul>
                </div>
            )}

            <p className="text-xs opacity-70 leading-relaxed">
                This alert is generated by AI pattern recognition and does not constitute a medical diagnosis.
                Please consult a qualified healthcare professional immediately.
            </p>
        </motion.div>
    );
}
