'use client';
import { useRef } from 'react';
import { Download } from 'lucide-react';

export default function PdfDownloadButton({ reportRef, patientName }) {
    const handleDownload = async () => {
        if (!reportRef?.current) return;

        // Dynamic import to avoid SSR issues
        const html2canvas = (await import('html2canvas')).default;
        const { jsPDF } = await import('jspdf');

        try {
            const element = reportRef.current;
            const canvas = await html2canvas(element, {
                scale: 2,
                useCORS: true,
                backgroundColor: '#ffffff',
                logging: false,
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();
            const imgWidth = pageWidth - 20;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            // Header
            pdf.setFillColor(0, 87, 217);
            pdf.rect(0, 0, pageWidth, 12, 'F');
            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(10);
            pdf.setFont(undefined, 'bold');
            pdf.text('CliniQ AI — Clinical Intake Report', 10, 8);
            pdf.setFontSize(7);
            pdf.text(new Date().toLocaleString(), pageWidth - 50, 8);

            // Content
            let yOffset = 16;
            let remainingHeight = imgHeight;

            while (remainingHeight > 0) {
                const sliceHeight = Math.min(remainingHeight, pageHeight - yOffset - 15);
                pdf.addImage(imgData, 'PNG', 10, yOffset, imgWidth, imgHeight, undefined, 'FAST', 0);

                remainingHeight -= sliceHeight;
                if (remainingHeight > 0) {
                    pdf.addPage();
                    yOffset = 10;
                } else {
                    break;
                }
            }

            // Footer
            const totalPages = pdf.internal.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                pdf.setPage(i);
                pdf.setFontSize(7);
                pdf.setTextColor(150);
                pdf.text(
                    `Generated by CliniQ AI | Page ${i} of ${totalPages} | ${new Date().toLocaleDateString()}`,
                    10,
                    pageHeight - 8
                );
            }

            const fileName = `CliniQ_AI_Report_${(patientName || 'Patient').replace(/\s+/g, '_')}_${Date.now()}.pdf`;
            pdf.save(fileName);
        } catch (error) {
            console.error('PDF generation error:', error);
            alert('Failed to generate PDF. Please try again.');
        }
    };

    return (
        <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-6 py-3 bg-white border-2 border-primary text-primary rounded-xl font-bold text-sm hover:bg-primary hover:text-white transition-all shadow-card hover:shadow-glow-blue"
        >
            <Download className="w-4 h-4" />
            Download Intake Report
        </button>
    );
}
